##
##  General settings
##
phonegap_path:             '~/Development/phonegap-2.6.0'
api_server:                'http://poochpapa.herokuapp.com' #This will be accessible through API_SERVER global var

##  Android settings
android:
   package:                'com.techgirlwonder.poochpapa'
